### ISSUE TITLE
Doesn't first show you the onboarding screen when you log in for the first time

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#212] opened 2021-07-26 20:30 UTC
Steps to reproduce: 
1. Create a new account
2. Sign in
3. You will see the profile screen show up for a few seconds before the onboarding screen appears

**Comment by aloverso** [comment] 2021-07-27 14:02
@Jesslax @skeeJay I think we talked about this one a few times since the start of the project. In order to let our pages be scraped by Googlebots and have better SEO, you need to show something to a non-logged-in user for a split-second before you redirect them to another page. It will always take a half-second or so for us to fetch a user's data, so for that first half-second, we will not know if they _should_ be on the roadmap page, or if they should be redirected elsewhere. 

We can change this behavior, but I want to make sure we're aware of the tradeoffs and alternatives. If we show a blank page for that half-second until we figure out where the user should be, then a googlebot will also see a blank page, and won't index any of the text on that page.

We can change this behavior individually page-to-page, though. Maybe the Roadmap page doesn't have all that much useful content that might be important for SEO, that's probably mostly more important Task pages anyways.

Does this make sense? What do you want to do?

**Comment by skeeJay** [comment] 2021-08-30 11:05
@Jesslax Closing this because it is expected behavior and I am not sure what an alternative would be. We should open a research story if we want to pursue.

**Closed by skeeJay** 2021-08-30 11:05 UTC
Labels: (:lady_beetle: ), needs spec
