### ISSUE TITLE
As Poppy, I should see an address form on license Task screen that matches our requirements

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#149] opened 2021-06-09 19:35 UTC
To summarize the outcomes of convo below:
- We will not be collecting municipality, for now
- State will not be editable
- Not yet using Address Line 2 for matching

QA:

- [x] Change the design for the state box to be greyed-out
- [x] "New Jersey"font color should be base-darkest (#1b1b1b) in the State field.
- [x] Change ZIP Code field to `input type="number"` so that only an integer can be typed into this field

**Comment by skeeJay** [comment] 2021-06-10 00:11
My personal opinions on these questions @aloverso @guy-nj:

1. I would not show a form field for state, I would assume it's always NJ right now. (But, is there any way to confirm this by scanning the table to see how many records have another state?)
2. I do, however, think we may need one for municipality. I can think of some situations where we might be dealing with a filing that is different than what was entered during onboarding. But we could pre-populate the field, however.
3. This is more of an open question that we may have to tweak over time. I think I'll have to understand how forgiving the current Address Line 1 matching is.

**Comment by guy-nj** [comment] 2021-06-10 17:02
1. I think we still need to show the State field as the standard address format. So it doesn't get the user thinking "Hmm,  the state is missing but I assume they know it's NJ since the zipcode is correct?" We can make it abbreviations "NJ" to save the space. 
2. Agreed on showing and prepopulating the municipality. 
3. @aloverso and I briefly discuss how we can avoid the technical issue from the address matching. We can ask about the business name and zipcode (and municipality) first. If it returns multiple results, we can ask the "street number" to avoid the issue of street/st or road/rd...etc. This seems an urgent design task for this sprint since it's blocking Anne's development.

**Comment by skeeJay** [comment] 2021-06-10 17:30
@guy-nj In regards to question 1: I agree we need to display "NJ." I am wondering if there is a "lightweight" way to do that, perhaps not in a full input box but very clearly "hardcoded." Mostly, I am wondering if it's possible to get Address Line 2, ZIP code, and "NJ" onto a single line, since ZIP code will always only be 5 characters long and NJ will always be only 2 characters long.

**Comment by guy-nj** [comment] 2021-06-11 20:32
Sure the Address line 2, Zipcode and State can fit together in one line. It's just a bit against the standard address hierarchy. A user might pause and think for 2 seconds and then get it. I am on the fence but don't have a better solution. See the mock:
<img width="472" alt="Screen Shot 2021-06-11 at 4 21 26 PM" src="https://user-images.githubusercontent.com/77984966/121744567-19842b80-cad1-11eb-86f4-b101fa6a8d24.png">

I still prefer keeping the State the standard dropdown. I would only change it to "hardcoded" only if we are sure there will be no use case that the user needs to edit the state. Otherwise we will need to revisit the design again.

**Comment by skeeJay** [comment] 2021-06-11 20:43
Sorry, I think I misspoke here. I thought there was a way to condense the design to three lines, but I didn't mean to break up the standard layout. I think what confused me is that it always goes city-state-zip, not city-zip-state, doesn't?

As far as the state goes: I think we are agreeing the user will never need to edit the state, and that that's confirmed by what @aloverso has heard from Consumer Affairs. We may need to revisit at some point, but for the foreseeable future, I think we are intentionally making NJ non-selectable. Anne should confirm that this is correct, though.

**Comment by guy-nj** [comment] 2021-06-14 13:53
Per discussion wth @skeeJay on Friday, we would have the City, grey-out NJ, and Zipcode fields in the 4th line on laptop view. On mobile, the grey-out NJ and Zipcode will move to the 5th line and City by itself in the 4th line. <img width="693" alt="Screen Shot 2021-06-11 at 5 21 27 PM" src="https://user-images.githubusercontent.com/77984966/121902660-86780b00-ccf5-11eb-9e68-97226e7e5d06.png">

**Comment by skeeJay** [comment] 2021-06-14 14:45
@guy-nj Notably, we do not actually have the city selection in the Dashboard right now. It may be unnecessary if we are asking for ZIP. cc @aloverso @Jesslax Even if municipality is unnecessary, does it become confusing NOT to ask for it? Or can we safely leave it out? Thoughts?

**Comment by guy-nj** [comment] 2021-06-14 14:55
I remember seeing municipality data in the spreadsheet Anne showed us the other day. And we can prepopulate the municipality data from the onboarding process. Am I missing something? I think missing zipcode and city in a address form would be confusing and the user might end up adding the zipcode or city into the address line 1 or 2 field.

**Comment by skeeJay** [comment] 2021-06-14 14:57
@guy-nj It all depends whether and how @aloverso is using it to do the match. Even if not using it, if we think it would be confusing to remove it, we could still ask for it and ignore it. There are a lot of options.

**Comment by aloverso** [comment] 2021-06-14 16:14
@skeeJay @guy-nj Yep this is exactly the 2nd question I had on this ticket initially. If you want to collect municipality, how do you want it to be used?

**Comment by skeeJay** [comment] 2021-06-14 16:27
I think we should decide how it's used from matching first. The presentation of the form will follow from that.

From my perspective, ZIP carries all the same information as municipality, and is a much cleaner match. I am trying to envision a matching situation where we would truly need the municipality name for the match.

**Comment by guy-nj** [comment] 2021-06-14 17:02
Agreed ZIP is better for matching and carries the same information. I do think showing the municipality is necessary to reduce the UI confusion.

**Comment by aloverso** [comment] 2021-06-14 17:41
imo, if we're not using the municipality dropdown, I think we should remove it. Having it presents all kinds of potential complications that there's no reason for us to have to deal with:
- users might expect their zip code to be prefilled from their municipality, which we established wouldn't work super well
- what if they enter a municipality and zip code that don't match? ideally we'd alert them? 
- what if they change their municipality to something other than what was selected on the onboarding screen? do we update their onboarding roadmap, or present them with that option?

We could just avoid having to deal with these questions by not showing the dropdown, especially if it's not actually providing user value. I'd err towards the thing with less work, and then ask people in user interviews if it's confusing to only ask for zipcode but not municipality. But I'm not sure the value of starting with that assumption.

**Comment by Jesslax** [comment] 2021-06-14 18:00
I agree, we should only ask for the information we need.

**Comment by aloverso** [comment] 2021-06-16 13:57
@skeeJay edited the story description to capture the convo here, is that accurate?
Do we also want to do research into address normalization to make the matching of Line 1 better? Or are we waiting until we actually integrate with the real data for that?

**Comment by skeeJay** [comment] 2021-06-16 16:14
@aloverso Description seems right to me. For address normalization, we probably need to look at the production data and see if they have normalized _that_ at all. Might be the next thing to ask after they give us access to production data.

**Comment by skeeJay** [comment] 2021-07-09 13:32
@guy-nj ^ QA

**Comment by guy-nj** [comment] 2021-07-09 19:59
@maitanavarro I added a note to fix "New Jersey" text color.

**Comment by skeeJay** [comment] 2021-07-12 16:52
@guy-nj does this address the font-color of `New Jersey`? Were you talking about the font-color? We may not have been specific enough. Other items LGTM.

**Comment by guy-nj** [comment] 2021-07-12 17:03
@skeeJay yes it meant the New Jersey font color in the State field. I was not specific in the story but Maita knew about this in our earlier conversation where I sahred a screenshot. I have fixed the description above and now it looks good to me on Dev!

**Comment by skeeJay** [comment] 2021-07-12 17:06
@guy-nj Okay, marking this as Ready to Deploy.

**Closed** 2021-07-12 21:11 UTC
Labels: (:star: ), size: :black_small_square:
