### ISSUE TITLE
As Poppy I'm not sure what all the different terms mean, and when I read about one term in one place and another term in another place, are they all talking about the same thing?

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#55] opened 2021-02-26 16:08 UTC

**Comment by skeeJay** [comment] 2021-04-01 14:40
@Jesslax Could we consider this is part of #73, or do you see it as a separate thing to research?

**Comment by Jesslax** [comment] 2021-04-01 14:42
@skeeJay agree, we can delete.

**Comment by skeeJay** [comment] 2021-04-01 14:43
Dupe of #73

**Closed by skeeJay** 2021-04-01 14:43 UTC
