### ISSUE TITLE
As Poppy, when I click next during onboarding, I should always arrive at the top of the next onboarding screen

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#123] opened 2021-05-03 17:44 UTC

**Comment by skeeJay** [comment] 2021-05-03 17:49
Dupe of #33

**Comment by skeeJay** [comment] 2021-05-05 12:52
Seems to work as I would expect, though @guy-nj would like to get your eyes on this too, just in case you had an idea of some other transition than what we're seeing.

**Comment by guy-nj** [comment] 2021-05-05 13:41
Looks the bug has been fixed. Looking good!

**Closed** 2021-05-05 22:33 UTC
Labels: (:beetle: )
