### ISSUE TITLE
Design: Explore next iteration of B.NJ.gov homepage design, hero image

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#409] opened 2021-09-08 14:54 UTC
**As** <PERSONA>
**I need to** <GOAL>
**So that** <OUTCOME>

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by Jesslax** [comment] 2021-09-14 20:02
duplicate of #388

**Closed** 2021-09-14 20:02 UTC
Labels: (:star: )
